# __Getting started with Julia__
__Index:__
1. How to print 
2. Assigning variables
3. Comments in Julia
4. Basic math syntax
5. Data Structures
    1. Tuples
    2. Dictionaries
    3. Arrays
6.  Loops
    1. while loops
    2. for loops
7. Conditionals


## __How to print__ 
In Julia we typically use _println()_

In [1]:
println("Hello Tor Vergata! I'm excited to be here!")

Hello Tor Vergata! I'm excited to be here!


## __Assigning variables__

All we need is a name, a value, and an equal's sign! 

Julia will deal automatically the types for us

In [2]:
my_int = 42
typeof(my_int)

Int64

In [3]:
my_float = 42.0
typeof(my_float)

Float64

In [4]:
my_string = "This is a string"
typeof(my_string)

String

For sure we can always reassign a value  (also of a different type!) to existing variables

In [5]:
my_int = "I'm not an int anymore"
println(my_int)

I'm not an int anymore


We can easily access any variable using the reference $

In [11]:
println("The value of my_float is $my_float")

The value of my_float is 42.0


## __Comments in Julia__

In [12]:
# This is a single line comment 

In [13]:
#=
This is a 
multiline
comment
=#

## __Basic math syntax__

In [6]:
sum = 3+4

7

In [7]:
diff = 10-3

7

In [8]:
ratio = 10/5

2.0

In [9]:
product = 5*2

10

In [10]:
modulus = 11%2

1

In [11]:
power = 10^2

100

## __Data Structures__
Once we start working with many pieces of data at once, it will be convenient for us to store data in structures like arrays or dictionaries rather than just relying on variables

### Tuples

We can create tuples by enclosing an ordered collection of elements in ( ).

Syntax:

(item1, item2, ...)

In [12]:
my_fav_books = ("Harry Potter", "Quantum Field Theory", "Flatlandia")

("Harry Potter", "Quantum Field Theory", "Flatlandia")

We can index into this tuple:

In [13]:
aux = my_fav_books[3]
println("One of my favourite books is $aux")

One of my favourite books is Flatlandia


but since tuples are immutable objects, __we can't update them__

In [14]:
my_fav_books[1] = "ERROR!"

MethodError: MethodError: no method matching setindex!(::Tuple{String,String,String}, ::String, ::Int64)

Julia also supports NamedTuples, e.g. (name1=item1, name2=item2, ...). Like regular tuples, NamedTuples are ordered so we can retrive their elements via indexing but also by their name: my_named_tuple.name1

### Dictionaries

If we have sets of data related to one another, we may choose to store that data in a dictionary. We can create a dictionary using the Dict() function, which we can initialize as an empty dictionary or one storing key, value pairs.

Syntax:

Dict(key1 => value1, key2 => value2, ...)

A good example is a contacts list, where we associate names with phone numbers.

In [23]:
my_dic = Dict("Alice" => "340 3732211", "Bob" => "348 8129296")

Dict{String,String} with 2 entries:
  "Alice" => "340 3732211"
  "Bob"   => "348 8129296"

In this example names and numbers are "keys" and "values" respectively. We can grab Alice's number using the associated key

In [16]:
my_dic["Alice"]

"340 3732211"

We can add Jenny's number as another entry as follows:


In [26]:
my_dic["Jenny"] = "326 2673889"
#let us inspect the dictionary
my_dic

Dict{String,String} with 2 entries:
  "Jenny" => "326 2673889"
  "Alice" => "340 3732211"

We can delete Bob from the dictionary and simultaneously grab his number by using pop!

In [24]:
bob_number = pop!(my_dic, "Bob")


"348 8129296"

In [27]:
my_dic

Dict{String,String} with 2 entries:
  "Jenny" => "326 2673889"
  "Alice" => "340 3732211"

## Arrays

Unlike tuples, arrays are mutable. Unlike dictionaries, arrays contain ordered collections.

We can create arrays by enclosing the collections in [ ]

Syntax:

[item2, item2, ...]

We can create an array with the Fibonacci sequence:


In [28]:
fibonacci =  [1, 1, 2, 3, 5, 8, 13]

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

Or we can create a mixed array:


In [29]:
mix = [3, 4, 5, "Hello", "TorVergata"]

5-element Array{Any,1}:
 3
 4
 5
  "Hello"
  "TorVergata"



Once we have an array, we can grab individual pieces of data from inside that array by indexing into the array. For example, if we want the third Fibonacci number listed in fibonacci, we write


In [30]:
fibonacci[3]

2

We can use indexing to edit an existing element of an array:

In [31]:
mix[1] = 100
mix

5-element Array{Any,1}:
 100
   4
   5
    "Hello"
    "TorVergata"

And yes, Julia is 1-based indexing, not 0-based like Python. "Wars are fought over lesser issues"

We can also add a new element to the array by using the _push!_ function:

In [32]:
push!(fibonacci, 21)
fibonacci

8-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13
 21

And we can remove it using the function _pop!_

In [33]:
pop!(fibonacci)
fibonacci

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

Be careful when you want to copy arrays!

In [35]:
my_arr = fibonacci

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [36]:
my_arr[1] = 100

100

In [37]:
fibonacci


7-element Array{Int64,1}:
 100
   1
   2
   3
   5
   8
  13

Editing my_arr caused fibonacci to get updated as well! 

In the above example, we didn't actually make a copy of fibonacci. We just created a new way to access the entries in the array bound to fibonacci.

If we'd like to make a copy of the array bound to fibonacci, we can use the copy function.

In [38]:
fibonacci[1] = 1
my_arr = copy(fibonacci)
my_arr[1] = 100
fibonacci

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

What we saw so far are the standard rules for creating arrays, bu typically in Julia we follow a different strategy: the idea is to create an undefined array of a given type and a given dimension. The syntax is:


In [43]:
a = Vector{Float64}(undef, 5) # Create a length 5 Vector (dimension 1 array) of Float64's with undefined values

for i in 1:length(a)
    a[i] = i^2
end
a

5-element Array{Float64,1}:
  1.0
  4.0
  9.0
 16.0
 25.0

Or, if we don't know a priori the dimension of the array we could use the push! function 

In [45]:
new_a = Vector{Float64}(undef, 0)

for i in 1:5
    push!(new_a, i^2)
end
new_a

5-element Array{Float64,1}:
  1.0
  4.0
  9.0
 16.0
 25.0

In [46]:
b = Matrix{Float64}(undef, 5,3) # Define a Matrix of Float64's of size (5,3) with undefined values

c = Array{Float64}(undef, 3, 4, 5, 6); # Define a (3, 4, 5, 6) Array of Int64's with undefined values

We can also make an array of similar size and shape via the function similar, or make an array of zeros/ones respectively:

In [49]:
d = similar(a)
e = zeros(5)
f = ones(5)
println("similar output:  ",d)
println("zeros output:  ",e)
println("ones output:  ", f)

similar output:  [2.2803760277e-314, 2.2803760435e-314, 2.2803760593e-314, 2.2803759803e-314, 2.280376012e-314]
zeros output:  [0.0, 0.0, 0.0, 0.0, 0.0]
ones output:  [1.0, 1.0, 1.0, 1.0, 1.0]


For sure, arrays  can be of arrays:

In [50]:
a = Vector{Vector{Float64}}(undef,2)
a[1] = [1, 2, 3]
a[2] = [8, 9, 6, 10]
a

2-element Array{Array{Float64,1},1}:
 [1.0, 2.0, 3.0]
 [8.0, 9.0, 6.0, 10.0]

## __Loops__

The while loop sintax is:


In [51]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]

i = 1
while i <= length(myfriends)
    friend = myfriends[i]
    println("Hi $friend, it's great to see you!")
    i += 1
end



Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


We could use the for loop to generate the same result as above

In [53]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]

for friend in myfriends
    println("Hi $friend, it's great to see you!")
end



Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


Note that we iterate over this array via column-major loops in order to get the best performance. More information about fast indexing of multidimensional arrays inside nested loops can be found at https://docs.julialang.org/en/v1/manual/performance-tips/#Access-arrays-in-memory-order,-along-columns-1

As another example, we  have:

In [54]:
m,n = 5, 5
A = zeros(m, n) # or equivalently A = fill(0,(m,n))

for i in 1:n, j in 1:m
    A[i,j] = i+j
end
A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

The more Julia way to create this addition table would have been with array comprehension:


In [55]:
C = [i+j for i in 1:n, j in 1:m]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

## __Conditionals__

For example, we might want to implement the FizzBuzz test: given a number, N, print "Fizz" if N is divisible by 3, "Buzz" if N is divisible by 5, and "FizzBuzz" if N is divisible by 3 and 5. Otherwise just print the number itself! 

In [58]:
N= 10
if (N % 3 == 0) && (N % 5 == 0) # `&&` means "AND"; % computes the remainder after division
    println("FizzBuzz")

elseif N % 3 == 0
    println("Fizz")

elseif N % 5 == 0
    println("Buzz")

else
    println(N)
end

Buzz


As a ternary operator, the conditional looks like

In [59]:
x = 10
y = 50
(x > y) ? println(x) : println(y)

50
